FROM node:14.17.0-alpine as build-step
RUN mkdir -p /app

WORKDIR /app

COPY package*.json /app

RUN yarn install

COPY . /app

RUN yarn build --prod

FROM nginx:1.19.2-alpine
COPY --from=build-step /app/dist/learning /usr/share/nginx/html
EXPOSE 4200:80
