version: '3'
services:
  web_app:
    container_name: 'web_app'
    build:
      context: .
      dockerfile: ./DockerFile
    networks:
      - onenetwork
    ports:
      - '4200:80'
networks:
 onenetwork:
   driver: bridge
